baseURL: https://www.gbb.is
title: Gummi's website
theme: hugo-coder
languageCode: en
defaultContentLanguage: "en"
paginate: 20
pygmentsStyle: "friendly"
pygmentsCodeFences: true
pygmentsCodeFencesGuessSyntax: true
enableEmoji: true
enableGitInfo: true

# This is for the <br> tags in the vim post
markup:
  goldmark:
    renderer:
      unsafe: true

params:
  author: "Guðmundur Björn Birkisson"
  description: "This is a space where I write about things that I find interesting and useful"
  keywords: "blog,developer,personal"
  info: ["Software Engineer"]
  avatarURL: "images/avatar.jpg"
  dateFormat: "2006-01-02"
  since: 2022
  commit: "https://github.com/gbbirkisson/gbb-is/tree"
  rtl: false

  # Specify light/dark colorscheme, supported values:
  # "auto" (use preference set by browser)
  # "dark" (dark background, light foreground)
  # "light" (light background, dark foreground) (default)
  colorScheme: "auto"
  hideColorSchemeToggle: false
  # Series see also post count
  maxSeeAlsoItems: 5
  customCSS: []
  customSCSS: []
  customJS: []

  csp:
    childsrc: ["'self'"]
    fontsrc:
      ["'self'", "https://fonts.gstatic.com", "https://cdn.jsdelivr.net/"]
    formaction: ["'self'"]
    framesrc: ["'self'"]
    imgsrc: ["'self'"]
    objectsrc: ["'none'"]
    stylesrc:
      [
        "'self'",
        "'unsafe-inline'",
        "https://fonts.googleapis.com/",
        "https://cdn.jsdelivr.net/",
      ]
    scriptsrc:
      [
        "'self'",
        "'unsafe-inline'",
        "https://www.google-analytics.com",
        "https://cdn.jsdelivr.net/",
      ]
    prefetchsrc: ["'self'"]
    # connect-src directive – defines valid targets for to XMLHttpRequest (AJAX), WebSockets or EventSource
    connectsrc: ["'self'", "https://www.google-analytics.com"]

  social:
    - name: "Github"
      icon: "fa fa-2x fa-github"
      target: "_blank"
      weight: 1
      url: "https://github.com/gbbirkisson/"

    - name: "LinkedIn"
      icon: "fa fa-2x fa-linkedin"
      target: "_blank"
      weight: 4
      url: "https://www.linkedin.com/in/gbbirkisson/"

taxonomies:
  category: "categories"
  series: "series"
  tag: "tags"
  author: "authors"

languages:
  en:
    languageName: ":uk:"
    menu:
      main:
        - name: "Posts"
          weight: "1"
          url: "posts/"

        - name: "Tags"
          weight: "2"
          url: "tags/"

        - name: "About"
          weight: "3"
          url: "about/"
